import { Poppins  } from 'next/font/google';
import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/common/header/Header";
import Footer from '@/components/ui/home/footer/Footer';

const poppins = Poppins({
  subsets: ['latin'],      
  weight: ['400', '600', '700'],  
  variable: '--font-poppins',     
});


export const metadata: Metadata = {
  title: "Food delivery app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={` ${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
          <Header />
            {children}
          <Footer />
      </body>
    </html>
  );
}
